name: flutter_dynamic_forms

description: A new flutter package to provide a solution for Server Driven forms
  in your Flutter application.

version: 0.0.1

homepage: null

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # For date formatting and other intl uses.
  intl: ^0.17.0

  # To create code for JSON serialization and deserialization.
  json_annotation: ^4.6.0

  # To create a rich text field in the form.
  html_editor_enhanced: ^2.5.0

dev_dependencies:
  # Generate files (JSON serialization & deserialization)
  build_runner: ^2.2.0

  # To generate api documentation for the package to be published.
  dartdoc: ^6.0.1

  # Flutter linting
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  # Dev dependencies for json_annotation
  json_serializable: ^6.3.1
